<?php require_once './templates/layout/header.phtml' ?>

<div class="container my-5 p-4 shadow-sm bg-light rounded">
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<form method='POST' action='verificarLogin'>
<h2 class="text-center text-black mb-4">Iniciar Sesion</h2>
    <div class='form-group'>
        <label for='user_name'>Nombre usuario</label>
        <input type='text' class='form-control' name='user_name' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary mt-2'>Login</button>
</form>
</div>
<?php require_once './templates/layout/footer.phtml' ?>