<?php 
require_once './templates/layout/header.phtml'; 
$isUpdate = isset($order);
?>

<div class="container my-5 p-4 shadow-sm bg-light rounded">
    <h2 class="text-center text-black mb-4"><?php if($isUpdate) :?>  
        Editar Orden 
        <?php else : ?>
        Agregar nueva orden
        <?php endif ?>
        </h2>

        <form action="<?php if ($isUpdate) {
    echo  BASE_URL .'modificarOrden/' . $order->id;
} else {
    echo  BASE_URL .'crearOrden';
} ?>" method="POST">
        <div class="form-floating mb-3">
            <div class="col-md-9">
                <div class="form-floating">
                
                <select class="form-select" aria-label="Disabled select example" name="product" required>
                     <option value="" selected disabled>Seleccione un producto</option>
                    <?php foreach($products as $product):?>
                        <option value="<?= $product->id ?>"><?= $product->name?></option>
                    <?php endforeach ?>    
                </select>
                <label for="product" class="form-label">Seleccione un producto</label> 
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="form-floating">
                    <input name="cant_products" required min="1" type="number" class="form-control" placeholder="Cantidad de productos" 
                        value="<?php if($isUpdate): echo $order->cant_products; endif ?>">
                    <label for="cant_products">Cantidad de productos</label>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating">
                    <input required name="date" type="date" step="0.01" class="form-control"  placeholder="Ingrese la fecha"
                        value="<?php if($isUpdate): echo $order->date; endif ?>">
                    <label for="date">Ingrese la fecha</label>
                </div>
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg">Guardar</button>
        </div>
    </form>
    
</div>

<?php 
require_once './templates/layout/footer.phtml';
?>