<?php 
require_once './templates/layout/header.phtml';
?>
  



<!-- L variable items contiene el nombre del item -->
<div class="container overflow-hidden text-center">
    <h2>ORDENES</h2>
    <h3>Seleccione la operacion que desea realizar</h3>
    <table class="table">
    <thead>
      <tr>
        <th scope="col">N° Orden</th>
        <th scope="col">Fecha</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Precio</th>
        <th scope="col">Modificar</th>
        <th scope="col">Eliminar</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($ordens as $order) :?>
      <tr>
        <th scope="row"><?php echo$order->id?></th>
        <td><?php echo $order->date ?></td>
        <td><?php echo $order->cant_products ?></td>
        <td><?php echo $order->total ?></td>
        <td><a href="<?php echo BASE_URL ?>formularioModificarOrden/<?php echo $order->id ?>" class="btn text-white btn-success">Modificar</a></td>
        <td><a href="<?php echo BASE_URL ?>eliminarOrden/<?php echo $order->id ?>" class="btn text-white btn-danger">Eliminar</a></td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
  <a class="btn btn-primary " href="<?php echo BASE_URL ?>formularioNuevaOrden">AGREGAR</a>



    
</div>
<?php 
require_once './templates/layout/footer.phtml';
?>