<?php require './templates/layout/header.phtml' ?>
<div class="container mt-3">
        <h2>Listado de Productos - Categorías</h2>
        <ul class="list-group">
            <?php foreach ($products as $product) { ?>
               <div>
               <li class="list-group-item d-flex justify-content-between align-items-center shadow-sm p-3 mb-3 rounded">
                    <a class="btn btn-warning " href="itemCategoria/<?= $product->id ?>" class="product-link"> <?= $product->name ?> </a>
                </li>
                </div>
            <?php } ?>
        </ul>
        <div class="text-center mt-4">
        <a href="<?php echo BASE_URL; ?>home" class="btn btn-primary mt-2" id="volver">VOLVER</a>
        </div>
        <?php require './templates/layout/footer.phtml'; ?>
        